"""initial schema

Revision ID: 6024333e2772
Revises: 
Create Date: 2026-07-17 22:48:28.495000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6024333e2772'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_minute_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_bucket_ip', 'client_minute_aggregates', ['bucket_ts', 'client_ip'], unique=False)
    op.create_index(op.f('ix_client_minute_aggregates_bucket_ts'), 'client_minute_aggregates', ['bucket_ts'], unique=False)
    op.create_index(op.f('ix_client_minute_aggregates_client_ip'), 'client_minute_aggregates', ['client_ip'], unique=False)
    op.create_index(op.f('ix_client_minute_aggregates_user'), 'client_minute_aggregates', ['user'], unique=False)
    op.create_table('domain_minute_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_bucket_domain', 'domain_minute_aggregates', ['bucket_ts', 'domain'], unique=False)
    op.create_index(op.f('ix_domain_minute_aggregates_bucket_ts'), 'domain_minute_aggregates', ['bucket_ts'], unique=False)
    op.create_index(op.f('ix_domain_minute_aggregates_domain'), 'domain_minute_aggregates', ['domain'], unique=False)
    op.create_table('minute_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('blocked_requests', sa.Integer(), nullable=False),
    sa.Column('allowed_requests', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minute_aggregates_bucket_ts'), 'minute_aggregates', ['bucket_ts'], unique=True)
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('hierarchy', sa.String(length=64), nullable=True),
    sa.Column('peer', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_blocked'), 'raw_events', ['blocked'], unique=False)
    op.create_index(op.f('ix_raw_events_client_ip'), 'raw_events', ['client_ip'], unique=False)
    op.create_index(op.f('ix_raw_events_domain'), 'raw_events', ['domain'], unique=False)
    op.create_index(op.f('ix_raw_events_timestamp'), 'raw_events', ['timestamp'], unique=False)
    op.create_index('ix_raw_events_ts_client', 'raw_events', ['timestamp', 'client_ip'], unique=False)
    op.create_index('ix_raw_events_ts_domain', 'raw_events', ['timestamp', 'domain'], unique=False)
    op.create_index(op.f('ix_raw_events_user'), 'raw_events', ['user'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_raw_events_user'), table_name='raw_events')
    op.drop_index('ix_raw_events_ts_domain', table_name='raw_events')
    op.drop_index('ix_raw_events_ts_client', table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_timestamp'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_domain'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_client_ip'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_blocked'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_minute_aggregates_bucket_ts'), table_name='minute_aggregates')
    op.drop_table('minute_aggregates')
    op.drop_index(op.f('ix_domain_minute_aggregates_domain'), table_name='domain_minute_aggregates')
    op.drop_index(op.f('ix_domain_minute_aggregates_bucket_ts'), table_name='domain_minute_aggregates')
    op.drop_index('ix_domain_bucket_domain', table_name='domain_minute_aggregates')
    op.drop_table('domain_minute_aggregates')
    op.drop_index(op.f('ix_client_minute_aggregates_user'), table_name='client_minute_aggregates')
    op.drop_index(op.f('ix_client_minute_aggregates_client_ip'), table_name='client_minute_aggregates')
    op.drop_index(op.f('ix_client_minute_aggregates_bucket_ts'), table_name='client_minute_aggregates')
    op.drop_index('ix_client_bucket_ip', table_name='client_minute_aggregates')
    op.drop_table('client_minute_aggregates')
    # ### end Alembic commands ###
