"""audit log and anomaly events

Revision ID: c3dd467754e8
Revises: 466aaa85c9f3
Create Date: 2026-07-18 17:21:20.517339

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c3dd467754e8'
down_revision: str | None = '466aaa85c9f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='anomalyseverity'), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_client_ip'), 'anomaly_events', ['client_ip'], unique=False)
    op.create_index(op.f('ix_anomaly_events_domain'), 'anomaly_events', ['domain'], unique=False)
    op.create_index(op.f('ix_anomaly_events_generated_at'), 'anomaly_events', ['generated_at'], unique=False)
    op.create_index(op.f('ix_anomaly_events_severity'), 'anomaly_events', ['severity'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('USER_CREATED', 'USER_ROLE_CHANGED', 'USER_PASSWORD_RESET', 'USER_DELETED', name='auditaction'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_actor_user_id'), 'audit_log_entries', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_target_user_id'), 'audit_log_entries', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_target_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_anomaly_events_severity'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_generated_at'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_domain'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_client_ip'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
